```yml
version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/recetas

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - recetas-mongo-data:/data/db

volumes:
  recetas-mongo-data:
```